module.exports = { 
	_schemaOrgURI: 	'http://schema.rdfs.org/all.json',
	// PREDEFINED NAMESPACES: ['xml', 'rdf', 'owl', 'rdfs']
	// XML / RDF
	_base:			'xml$base',
	_lang:			'xml$lang',
	_rdf:			'rdf$RDF',
	_id:			'rdf$ID',
	_resource:		'rdf$resource',
	_about:			'rdf$about',
	_type: 			'rdf$type',
	// OWL
	_thing:			'owl$Thing',
	_ontology:		'owl$Ontology',
	_class:			'owl$Class',
	_datatype:		'owl$DatatypeProperty',
	_object:		'owl$ObjectProperty',
	_functionalP:	'owl$FunctionalProperty',
	_transitiveP:	'owl$TransitiveProperty',
	_symmetricP:	'owl$SymmetricProperty',
	_equivalentC:	'owl$equivalentClass',
	_equivalentP:	'owl$equivalentProperty',
	_oneOf:			'owl$oneOf',
	_unionOf:		'owl$unionOf',
	_intersectionOf:'owl$intersectionOf',
	_complementOf:	'owl$complementOf',
	_disjointWith:	'owl$disjointWith',
	_restriction: 	'owl$Restriction',
	_cardinality: 	'owl$cardinality',
	_minCardinality:'owl$minCardinality',
	_maxCardinality:'owl$maxCardinality',
	_onProperty: 	'owl$onProperty',
	_allValuesFrom: 'owl$allValuesFrom',
	_someValuesFrom:'owl$someValuesFrom',
	_hasValue: 		'owl$hasValue',
	// RDFS
	_subClassOf:	'rdfs$subClassOf',
	_subPropertyOf: 'rdfs$subPropertyOf',
	_domain:		'rdfs$domain',
	_range:			'rdfs$range',
	_label:			'rdfs$label',
	_comment:  		'rdfs$comment'
}